services:
  db:
    image: postgres:16
    container_name: demo_redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - demo-redis-data:/var/lib/postgresql/data
  redis-node-1:
    image: redis:8
    container_name: redis-node-1
    network_mode: "host"
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    volumes:
      - redis-node-1:/data
      - ./redis-node-1.conf:/usr/local/etc/redis/redis.conf
  redis-node-2:
    image: redis:8
    container_name: redis-node-2
    network_mode: "host"
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    volumes:
      - redis-node-2:/data
      - ./redis-node-2.conf:/usr/local/etc/redis/redis.conf
  redis-node-3:
    image: redis:8
    container_name: redis-node-3
    network_mode: "host"
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    volumes:
      - redis-node-3:/data
      - ./redis-node-3.conf:/usr/local/etc/redis/redis.conf
  redis-node-4:
    image: redis:8
    container_name: redis-node-4
    network_mode: "host"
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    volumes:
      - redis-node-4:/data
      - ./redis-node-4.conf:/usr/local/etc/redis/redis.conf
  redis-node-5:
    image: redis:8
    container_name: redis-node-5
    network_mode: "host"
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    volumes:
      - redis-node-5:/data
      - ./redis-node-5.conf:/usr/local/etc/redis/redis.conf
  redis-node-6:
    image: redis:8
    container_name: redis-node-6
    network_mode: "host"
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    volumes:
      - redis-node-6:/data
      - ./redis-node-6.conf:/usr/local/etc/redis/redis.conf
volumes:
  demo-redis-data:
  redis-node-1:
  redis-node-2:
  redis-node-3:
  redis-node-4:
  redis-node-5:
  redis-node-6: