spring:
  config:
    import: file:.env[.properties]
  application:
    name: learnredis
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      group-id: group-1
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 1

  jackson:
    serialization:
      write-date-keys-as-timestamps: false
jwt:
  accessExpiration: 86400
  refreshExpiration: 2592000
  secret: ${JWT_SECRET}

vetc:
  api:
    base-url: http://localhost:8081/api/test