spring:
  config:
    import: file:.env[.properties]
  application:
    name: learnredis
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}

jwt:
  accessExpiration: 86400
  refreshExpiration: 2592000
  secret: 2f8925eaa600fb7578d7cfe32c547370e66fb3ac87d79f2ce3a584689f54bb8c